[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.9"
rand = "0.9.2"
fuse = "0.3.1"
log = "0.4.29"
env_logger = "0.10"
time = "0.1.45"
libc = "0.2.178"
redis = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
